import fs from "node:fs/promises";
import path from "node:path";

const readJson = async (file, fallback = "[]") => JSON.parse(await fs.readFile(file, "utf8").catch(() => fallback));
const config = await readJson("config.json", "{}");
const storedOffers = await readJson("data/offers.json");
const status = await readJson("data/status.json", "{}");
const creators = await readJson("data/creators.json", '{"enabled":false,"entries":[]}');
const partners = await readJson("data/direct-partners.json");
const linkPolicy = await readJson("data/impact-link-policy.json", "{}");
const base = (process.env.SITE_URL || "https://example.github.io/angebotslotse").replace(/\/$/, "");
const email = process.env.CONTACT_EMAIL || "joellehrheuer@gmail.com";
const legalName = process.env.LEGAL_NAME || "Joel Leroy Lehrheuer";
const legalAddress = process.env.LEGAL_ADDRESS || "Rathausstraße 4, 52072 Aachen, Deutschland";
const analyticsToken = /^[a-f0-9]{32}$/i.test(process.env.CLOUDFLARE_WEB_ANALYTICS_TOKEN ?? "") ? process.env.CLOUDFLARE_WEB_ANALYTICS_TOKEN : "";
const googleVerification = /^[A-Za-z0-9_-]+$/.test(process.env.GOOGLE_SITE_VERIFICATION ?? "") ? process.env.GOOGLE_SITE_VERIFICATION : "";
const out = "dist";
const esc = value => String(value ?? "").replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const json = value => JSON.stringify(value).replace(/</g, "\\u003c");
const labels = {"technik":"Technik","gaming":"Gaming","audio-musik":"Audio & Musik","computer":"Computer","zubehoer":"Zubehör","haushalt":"Haushalt","werkzeug":"Werkzeug","mode":"Mode","freizeit":"Freizeit","sonstiges":"Weitere"};
const categories = ["gaming","technik","computer","audio-musik","zubehoer","haushalt","werkzeug","mode","freizeit","sonstiges"];
const isQuarantined = offer => (linkPolicy.quarantinedAdvertisers ?? []).some(rule =>
  (rule.advertiserId && String(rule.advertiserId) === String(offer.advertiserId)) ||
  (rule.advertiserName && String(rule.advertiserName).toLowerCase() === String(offer.advertiser).toLowerCase()));
const now = new Date();
const offers = storedOffers.filter(o => !isQuarantined(o) && (!o.endDate || new Date(o.endDate) > now));
const isDeal = o => Boolean(o.endDate || o.voucherCode || (o.currentPrice != null && o.previousPrice > o.currentPrice) || o.source !== "direct");
const currentDeals = offers.filter(isDeal);
const evergreen = offers.filter(o => !isDeal(o));
const creatorByName = new Map(creators.entries.map(item => [item.name.toLowerCase(), item]));
const url = suffix => `${base}${suffix}`;
const money = (value, currency = "EUR") => new Intl.NumberFormat("de-DE", {style:"currency",currency:currency || "EUR"}).format(value);
const discount = o => o.currentPrice != null && o.previousPrice > o.currentPrice ? Math.round((1-o.currentPrice/o.previousPrice)*100) : null;
const comparisonGroups = new Map();
for (const offer of offers) if (offer.productId && offer.currentPrice != null) {
  const key = `${offer.productId}:${offer.currency || "EUR"}`;
  comparisonGroups.set(key, [...(comparisonGroups.get(key) || []), offer].sort((a,b)=>a.currentPrice-b.currentPrice));
}
const comparisonFor = offer => comparisonGroups.get(`${offer.productId}:${offer.currency || "EUR"}`)?.filter(row=>row.id!==offer.id) || [];

const navGroups = [
  ["Entdecken", [["Angebote","/#aktuelle-deals"],["Aktuelle Deals","/#aktuelle-deals"],["Dauerangebote","/#dauerangebote"],["Kategorien","/kategorien.html"],["Newsletter","/#newsletter"],["Feedback / Kontakt","/kontakt.html"]]],
  ["Kategorien", categories.filter(c=>c!=="sonstiges").map(c=>[labels[c],`/kategorie/${c}.html`])],
  ["Social Media / Projekte", ["Twitch","YouTube","Instagram","Spotify","Snapchat","Discord","Buch","Merch-Shop"].map(name=>[name,creatorByName.get(name.toLowerCase())?.url||"/#projekte",true]).concat([["TikTok (folgt)","/#projekte"]])],
  ["Information", [["Über uns","/ueber.html"],["Affiliate-Hinweis","/affiliate.html"],["Datenschutz","/datenschutz.html"],["Impressum","/impressum.html"],["Status","/status.html"]]]
];
const nav = `<header class="site-header"><a class="brand" href="${url("/")}"><span>AL</span><b>Angebotslotse</b></a><a class="header-deals" href="${url("/#aktuelle-deals")}">Deals entdecken</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav"><span></span><span></span><span></span><i class="sr-only">Menü öffnen</i></button><nav id="main-nav" aria-label="Hauptnavigation"><div class="nav-panel">${navGroups.map(([title,links])=>`<section><strong>${title}</strong>${links.map(([name,href,external])=>`<a href="${external?esc(href):url(href)}"${external?' rel="me noopener"':""}>${esc(name)}</a>`).join("")}</section>`).join("")}</div></nav></header>`;
const footer = `<footer><div><a class="brand footer-brand" href="${url("/")}"><span>AL</span><b>Angebotslotse</b></a><p>Echte Angebote aus erlaubten Quellen. Transparent als Werbung gekennzeichnet.</p></div><nav aria-label="Rechtliches"><a href="${url("/affiliate.html")}">Affiliate-Hinweis</a><a href="${url("/datenschutz.html")}">Datenschutz</a><a href="${url("/impressum.html")}">Impressum</a><a href="${url("/kontakt.html")}">Kontakt</a><a href="${url("/status.html")}">Status</a></nav></footer>`;
function page({title,description,body,canonical="/",schema=null,socialImage=true,indexable=true}) {
  const analytics=analyticsToken?`<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='${json({token:analyticsToken})}'></script>`:"";
  const image=socialImage?`<meta property="og:image" content="${url("/og.png")}"><meta property="og:image:alt" content="Angebotslotse – echte Deals klar eingeordnet"><meta name="twitter:image" content="${url("/og.png")}">`:"";
  return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Angebotslotse</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${indexable?"index,follow,max-image-preview:large":"noindex,follow"}"><link rel="canonical" href="${url(canonical)}"><link rel="icon" href="${url("/favicon.svg")}" type="image/svg+xml">${googleVerification?`<meta name="google-site-verification" content="${esc(googleVerification)}">`:""}<meta property="og:type" content="website"><meta property="og:site_name" content="Angebotslotse"><meta property="og:locale" content="de_DE"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url(canonical)}">${image}<meta name="twitter:card" content="${socialImage?"summary_large_image":"summary"}"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><link rel="stylesheet" href="${url("/styles.css")}"><link rel="stylesheet" href="${url("/enhancements.css")}">${schema?`<script type="application/ld+json">${json(schema)}</script>`:""}<script src="${url("/app.js")}" defer></script>${analytics}</head><body>${nav}<main>${body}</main>${footer}</body></html>`;
}
const placeholder=o=>`<div class="product-image placeholder" role="img" aria-label="Kein offizielles Produktbild verfügbar"><span>${esc((o.advertiser||"AL").slice(0,2).toUpperCase())}</span><small>Bild nicht verfügbar</small></div>`;
const imageFor=o=>o.imageUrl?`<div class="product-image"><img src="${esc(o.imageUrl)}" alt="${esc(o.title)}" loading="lazy" referrerpolicy="no-referrer"></div>`:placeholder(o);
const card=o=>{const pct=discount(o);return `<article class="deal-card" data-search="${esc(`${o.title} ${o.description} ${o.advertiser} ${o.category}`.toLowerCase())}" data-category="${esc(o.category)}">${imageFor(o)}<div class="deal-content"><div class="card-top"><span class="pill">${esc(labels[o.category]||o.category)}</span>${pct?`<span class="discount">-${pct} %</span>`:""}</div><p class="merchant">${esc(o.advertiser)}</p><h3><a href="${url(`/angebote/${esc(o.slug)}.html`)}">${esc(o.title)}</a></h3>${o.platform?`<p class="platform">${esc(o.platform)}</p>`:""}${o.currentPrice!=null?`<div class="price"><strong>${money(o.currentPrice,o.currency)}</strong>${o.previousPrice?`<del>${money(o.previousPrice,o.currency)}</del>`:""}</div>`:`<p class="price-note">Preis beim Anbieter prüfen</p>`}${o.voucherCode?`<p class="voucher">Code: <code>${esc(o.voucherCode)}</code></p>`:""}${o.endDate?`<p class="countdown" data-countdown="${esc(o.endDate)}">Endet am ${new Intl.DateTimeFormat("de-DE").format(new Date(o.endDate))}</p>`:""}<a class="button" rel="sponsored noopener" href="${esc(o.trackingUrl)}" aria-label="Werbelink: ${esc(o.title)} bei ${esc(o.advertiser)}">Zum Angebot <span aria-hidden="true">↗</span></a><small class="ad-label">Werbelink</small></div></article>`};
const offerSection=(id,title,copy,items,limit=6)=>items.length?`<section class="deal-section" id="${id}"><div class="section-head"><div><span class="eyebrow">${esc(copy)}</span><h2>${esc(title)}</h2></div>${items.length>limit?`<a href="${url("/kategorien.html")}">Alle ansehen →</a>`:""}</div><div class="deal-grid">${items.slice(0,limit).map(card).join("")}</div></section>`:"";
const categoryTiles=categories.filter(c=>c!=="sonstiges").map(c=>`<a href="${url(`/kategorie/${c}.html`)}"><span>${esc(labels[c])}</span><b>${offers.filter(o=>o.category===c).length}</b></a>`).join("");
const creatorModule=creators.enabled?`<section class="creators" id="projekte"><div class="section-head"><div><span class="eyebrow">Klar getrennt vom Dealbereich</span><h2>Eigene Projekte & Kanäle</h2></div></div><div class="project-grid">${creators.entries.map(c=>`<a class="project-card" href="${esc(c.url)}" rel="me noopener"><span>${esc(c.name)}</span><p>${esc(c.description)}</p><b>Öffnen ↗</b></a>`).join("")}</div></section>`:"";
const activePartners=partners.filter(p=>p.enabled&&p.id!=="razer");
const partnerSection=`<section class="partner-section"><span class="eyebrow">Bestätigte Quellen</span><h2>Partner & Shops</h2><div>${activePartners.map(p=>`<a href="${esc(p.trackingUrl)}" rel="sponsored noopener"><strong>${esc(p.name)}</strong><small>Werbelink ↗</small></a>`).join("")}</div></section>`;
const updated=status.lastSuccessfulUpdate?new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(status.lastSuccessfulUpdate)):"ausstehend";
const homeBody=`<section class="hero"><div><span class="eyebrow">Angebote aus geprüften Quellen</span><h1>Gute Deals.<br><em>Sicher gelotst.</em></h1><p>Aktuelle Aktionen und verlässliche Partnerangebote – ohne Fake-Preise, künstliche Timer oder kopierte Produktbilder.</p><div class="hero-actions"><a class="button primary" href="#aktuelle-deals">Top-Deals ansehen</a><a class="text-link" href="${url("/kategorien.html")}">Kategorien entdecken →</a></div></div><aside><strong>${offers.length}</strong><span>aktive Angebote</span><small>Aktualisiert: ${esc(updated)} Uhr</small></aside></section><section class="trust"><span>✓ Offizielle Datenquellen</span><span>✓ Dreimal täglich aktualisiert</span><span>✓ Werbelinks klar markiert</span></section>${offerSection("aktuelle-deals","🔥 Aktuelle Top-Deals","Jetzt interessant",currentDeals.slice(0,6))}<section class="categories"><div class="section-head"><div><span class="eyebrow">Schneller ans Ziel</span><h2>Kategorien</h2></div></div><div class="category-grid">${categoryTiles}</div></section>${offerSection("stark-reduziert","Stark reduziert","Nur echte Vergleichspreise",offers.filter(o=>discount(o)).sort((a,b)=>discount(b)-discount(a)))}${offerSection("gaming-deals","Gaming-Deals","Games & Zubehör",offers.filter(o=>o.category==="gaming"))}${offerSection("technik-deals","Technik-Deals","Elektronik im Blick",offers.filter(o=>["technik","computer","zubehoer"].includes(o.category)))}${offerSection("audio-deals","Audio & Musik","Studio, Instrumente & Plugins",offers.filter(o=>o.category==="audio-musik"))}${offerSection("dauerangebote","Dauerangebote & Partner","Langfristige Einstiegsseiten",evergreen)}<section class="newsletter" id="newsletter"><div><span class="eyebrow">Newsletter</span><h2>Gute Angebote, nicht mehr Lärm.</h2><p>Der Newsletter wird DSGVO-konform mit Double-Opt-in und Abmeldung vorbereitet. Bis ein geprüfter Versanddienst verbunden ist, werden hier keine E-Mail-Adressen erfasst.</p></div><span class="coming-soon">In Vorbereitung</span></section>${creatorModule}${partnerSection}`;

await fs.rm(out,{recursive:true,force:true}); await fs.mkdir(path.join(out,"angebote"),{recursive:true}); await fs.mkdir(path.join(out,"kategorie"),{recursive:true}); await fs.cp("public",out,{recursive:true});
await fs.writeFile(path.join(out,"index.html"),page({title:"Aktuelle Deals und Angebote für Deutschland",description:"Echte aktuelle Deals, Gutscheine und Partnerangebote aus erlaubten Quellen – transparent geprüft und ohne Fake-Rabatte.",body:homeBody,schema:{"@context":"https://schema.org","@type":"WebSite",name:config.siteName,alternateName:"Angebotslotse Deutschland",url:`${base}/`,inLanguage:"de-DE"}}));
for(const o of offers){const pct=discount(o);const alternatives=comparisonFor(o);const entity=o.currentPrice!=null?{"@type":"Product",name:o.title,image:o.imageUrl||undefined,sku:o.productId||undefined,offers:{"@type":"Offer",url:`${base}/angebote/${o.slug}.html`,price:o.currentPrice,priceCurrency:o.currency||"EUR",validThrough:o.endDate||undefined,seller:{"@type":"Organization",name:o.advertiser}}}:{"@type":"Offer",name:o.title,url:`${base}/angebote/${o.slug}.html`,validThrough:o.endDate||undefined,seller:{"@type":"Organization",name:o.advertiser}};const comparison=alternatives.length?`<section class="comparison"><h2>Preisvergleich</h2><p>Abgleich über die eindeutige Produktkennung der offiziellen Quellen.</p><div>${[o,...alternatives].sort((a,b)=>a.currentPrice-b.currentPrice).map((row,index)=>`<a href="${esc(row.trackingUrl)}" rel="sponsored noopener"><span>${esc(row.advertiser)}</span><strong>${money(row.currentPrice,row.currency)}</strong>${index===0?"<em>Günstigstes Angebot</em>":""}</a>`).join("")}</div></section>`:"";const body=`<article class="detail"><a class="back" href="${url("/#aktuelle-deals")}">← Alle Angebote</a><div class="detail-grid">${imageFor(o)}<div><div class="card-top"><span class="pill">${esc(labels[o.category]||o.category)}</span>${pct?`<span class="discount">-${pct} %</span>`:""}</div><p class="merchant">${esc(o.advertiser)}</p><h1>${esc(o.title)}</h1><p class="lead">${esc(o.description||"Details und Bedingungen direkt beim Anbieter prüfen.")}</p>${o.currentPrice!=null?`<div class="price large"><strong>${money(o.currentPrice,o.currency)}</strong>${o.previousPrice?`<del>${money(o.previousPrice,o.currency)}</del>`:""}</div>`:""}${o.voucherCode?`<p class="voucher">Gutscheincode: <code>${esc(o.voucherCode)}</code></p>`:""}${o.endDate?`<p class="countdown" data-countdown="${esc(o.endDate)}">Gültig bis ${new Intl.DateTimeFormat("de-DE").format(new Date(o.endDate))}</p>`:""}<a class="button primary" rel="sponsored noopener" href="${esc(o.trackingUrl)}">Werbelink beim Anbieter öffnen ↗</a></div></div>${comparison}${o.terms?`<section><h2>Bedingungen</h2><p>${esc(o.terms)}</p></section>`:""}<p class="notice">Bei einem Kauf über diesen Werbelink können wir eine Provision erhalten. Maßgeblich sind Preis, Verfügbarkeit und Bedingungen auf der Händlerseite.</p></article>`;await fs.writeFile(path.join(out,"angebote",`${o.slug}.html`),page({title:o.title,description:o.description||`Angebot von ${o.advertiser}.`,canonical:`/angebote/${o.slug}.html`,body,socialImage:Boolean(o.imageUrl),schema:{"@context":"https://schema.org","@graph":[{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Angebote",item:`${base}/`},{"@type":"ListItem",position:2,name:o.title,item:`${base}/angebote/${o.slug}.html`}]},entity]}}));}
for(const category of categories){const rows=offers.filter(o=>o.category===category);await fs.writeFile(path.join(out,"kategorie",`${category}.html`),page({title:`${labels[category]}-Angebote`,description:`Aktuelle ${labels[category]}-Deals und Partnerangebote aus erlaubten Quellen.`,canonical:`/kategorie/${category}.html`,body:`<section class="listing"><a class="back" href="${url("/kategorien.html")}">← Kategorien</a><span class="eyebrow">${rows.length} aktive Einträge</span><h1>${esc(labels[category])}</h1><div class="deal-grid">${rows.length?rows.map(card).join(""):`<div class="empty"><h2>Noch keine Quelldaten</h2><p>Passende Angebote erscheinen automatisch, sobald eine angeschlossene offizielle Quelle sie liefert.</p></div>`}</div></section>`}));}
await fs.writeFile(path.join(out,"kategorien.html"),page({title:"Alle Angebotskategorien",description:"Gaming, Technik, Computer, Audio, Haushalt und weitere Angebotskategorien.",canonical:"/kategorien.html",body:`<section class="listing"><span class="eyebrow">Alle Bereiche</span><h1>Kategorien</h1><div class="category-grid large">${categoryTiles}</div></section>`}));
const info={"ueber.html":["Über Angebotslotse","Angebotslotse bündelt Händleraktionen aus erlaubten Affiliate-Schnittstellen und bestätigten Direktpartnerschaften. Laufzeit, Region und Datenqualität werden automatisiert geprüft. Eigene Projekte bleiben klar vom Dealbereich getrennt.","/ueber.html"],"affiliate.html":["Affiliate-Hinweis","Ausgehende Angebotslinks sind als Werbelink gekennzeichnet und mit rel=\"sponsored\" markiert. Bei einer vergüteten Aktion kann der Betreiber eine Provision erhalten; für Nutzer entstehen dadurch grundsätzlich keine zusätzlichen Kosten. Die Vergütung belegt weder Qualität noch Preisvorteil. Maßgeblich ist stets die Zielseite.","/affiliate.html"],"datenschutz.html":["Datenschutzerklärung",`Verantwortlicher: ${legalName}, ${legalAddress}. E-Mail: ${email}.\nHosting: Diese statische Website wird über GitHub Pages bereitgestellt. GitHub kann zur sicheren Auslieferung technische Server-Logdaten verarbeiten.\nAffiliate-Links: Erst beim Anklicken eines gekennzeichneten externen Links wird Angebotslotse verlassen. Awin, Impact oder der direkte Partner können dann Daten nach ihren eigenen Datenschutzinformationen verarbeiten.\nCookies und Analyse: Angebotslotse setzt ohne aktivierte Besucherstatistik keine eigenen Analyse- oder Marketing-Cookies ein.\nKontakt: Per E-Mail übermittelte Angaben werden nur zur Bearbeitung und aufgrund gesetzlicher Pflichten verarbeitet.\nBetroffenenrechte: Im gesetzlichen Rahmen bestehen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit, Widerspruch und Beschwerde.\nStand: 4. September 2026.`,"/datenschutz.html"],"impressum.html":["Impressum",`Angaben gemäß § 5 DDG\n${legalName}\n${legalAddress}\nKontakt: ${email}\nVerantwortlich gemäß § 18 Abs. 2 MStV: ${legalName}, Anschrift wie vorstehend.`,"/impressum.html"],"kontakt.html":["Feedback & Kontakt",`Fragen, Feedback, Korrekturhinweise oder Meldungen zu abgelaufenen Angeboten bitte per E-Mail an ${email}. Wir bieten keine individuelle Kauf- oder Rechtsberatung.`,"/kontakt.html"]};
if(analyticsToken)info["datenschutz.html"][1]=info["datenschutz.html"][1].replace("Cookies und Analyse: Angebotslotse setzt ohne aktivierte Besucherstatistik keine eigenen Analyse- oder Marketing-Cookies ein.","Besucherstatistik: Angebotslotse nutzt Cloudflare Web Analytics für zusammengefasste Aufruf- und Leistungsdaten. Beim Laden des Cloudflare-Skripts und Übertragen der Messung wird die IP-Adresse transportbedingt verarbeitet. Cloudflare erklärt, Web Analytics verwende keine Cookies, erstelle keine individuellen Profile, verfolge Besucher nicht websiteübergreifend und erhebe oder verwende keine personenbezogenen Besucherdaten. Es wird kein Marketing-Tracking eingesetzt.");
for(const [file,[title,copy,canonical]] of Object.entries(info))await fs.writeFile(path.join(out,file),page({title,description:copy.slice(0,155),canonical,body:`<section class="text-page"><span class="eyebrow">Information</span><h1>${esc(title)}</h1>${copy.split("\n").map(p=>`<p>${esc(p)}</p>`).join("")}</section>`}));
const sourceRows=Object.entries(status.sources||{}).map(([name,s])=>`<div><dt>${esc(name)}</dt><dd>${esc(s.state)} · ${Number(s.count)||0} Datensätze</dd></div>`).join("");
await fs.writeFile(path.join(out,"status.html"),page({title:"Systemstatus",description:"Status der Angebotsquellen und letzten Aktualisierung.",canonical:"/status.html",body:`<section class="text-page"><span class="eyebrow">Transparenz</span><h1>Systemstatus</h1><div class="status ${esc(status.state)}"><strong>${status.state==="ok"?"System betriebsbereit":"Aktualisierung eingeschränkt"}</strong><p>${esc(status.message)}</p></div><dl><div><dt>Veröffentlichte Angebote</dt><dd>${offers.length}</dd></div><div><dt>Letztes Update</dt><dd>${esc(updated)}</dd></div>${sourceRows}</dl></section>`}));
await fs.writeFile(path.join(out,"404.html"),page({title:"Seite nicht gefunden",description:"Die angeforderte Seite wurde nicht gefunden.",canonical:"/404.html",indexable:false,body:`<section class="text-page"><span class="eyebrow">Fehler 404</span><h1>Hier ist nichts mehr.</h1><p>Das Angebot ist möglicherweise abgelaufen oder wurde aus Qualitätsgründen entfernt.</p><a class="button primary" href="${url("/")}">Zur Startseite</a></section>`}));
const sitemapUrls=["/","/kategorien.html",...categories.map(c=>`/kategorie/${c}.html`),...Object.values(info).map(x=>x[2]),"/status.html",...offers.map(o=>`/angebote/${o.slug}.html`)];
await fs.writeFile(path.join(out,"sitemap.xml"),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${sitemapUrls.map(p=>`<url><loc>${esc(url(p))}</loc></url>`).join("")}</urlset>\n`);await fs.writeFile(path.join(out,"robots.txt"),`User-agent: *\nAllow: /\nSitemap: ${url("/sitemap.xml")}\n`);
await fs.writeFile(path.join(out,"build-report.json"),`${JSON.stringify({offers:offers.length,images:offers.filter(o=>o.imageUrl).length,prices:offers.filter(o=>o.currentPrice!=null).length,discounts:offers.filter(o=>discount(o)).length,countdowns:offers.filter(o=>o.endDate).length,currentDeals:currentDeals.length,evergreen:evergreen.length,quarantined:storedOffers.length-offers.length},null,2)}\n`);
console.log(`V2 gebaut: ${offers.length} Angebote (${currentDeals.length} aktuell, ${evergreen.length} dauerhaft).`);
