import fs from "node:fs/promises";
import path from "node:path";

const config = JSON.parse(await fs.readFile("config.json", "utf8"));
const offers = JSON.parse(await fs.readFile("data/offers.json", "utf8"));
const status = JSON.parse(await fs.readFile("data/status.json", "utf8"));
const base = (process.env.SITE_URL || "https://example.github.io/angebotslotse").replace(/\/$/, "");
const email = process.env.CONTACT_EMAIL || "[E-MAIL-ADRESSE EINTRAGEN]";
const legalName = process.env.LEGAL_NAME || "[VOLLSTÄNDIGEN NAMEN EINTRAGEN]";
const legalAddress = process.env.LEGAL_ADDRESS || "[VOLLSTÄNDIGE LADUNGSFÄHIGE ANSCHRIFT EINTRAGEN]";
const out = "dist";
await fs.rm(out, { recursive: true, force: true });
await fs.mkdir(path.join(out, "angebote"), { recursive: true });
await fs.cp("public", out, { recursive: true });
const esc = value => String(value ?? "").replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const json = value => JSON.stringify(value).replace(/</g, "\\u003c");
const nav = `<header><a class="brand" href="${base}/"><span>AL</span>Angebotslotse</a><nav aria-label="Hauptnavigation"><a href="${base}/#angebote">Angebote</a><a href="${base}/kategorien.html">Kategorien</a><a href="${base}/ueber.html">Über uns</a></nav></header>`;
const footer = `<footer><div><strong>Angebotslotse</strong><p>Aktuelle Affiliate-Angebote, sachlich aufbereitet.</p></div><nav aria-label="Rechtliches"><a href="${base}/affiliate.html">Affiliate-Hinweis</a><a href="${base}/datenschutz.html">Datenschutz</a><a href="${base}/impressum.html">Impressum</a><a href="${base}/kontakt.html">Kontakt</a><a href="${base}/status.html">Status</a></nav></footer>`;
function page({ title, description, body, canonical = "/", schema = null }) {
  return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Angebotslotse</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${base}${canonical}"><link rel="icon" href="${base}/favicon.svg" type="image/svg+xml"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${base}${canonical}"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="${base}/styles.css">${schema ? `<script type="application/ld+json">${json(schema)}</script>` : ""}<script src="${base}/app.js" defer></script></head><body>${nav}<main>${body}</main>${footer}</body></html>`;
}
const card = o => `<article class="card" data-search="${esc(`${o.title} ${o.description} ${o.advertiser} ${o.category}`.toLowerCase())}"><div class="card-top"><span class="pill">${esc(o.category)}</span><span>${o.type === "voucher" ? "Gutschein" : "Aktion"}</span></div><h3><a href="${base}/angebote/${esc(o.slug)}.html">${esc(o.title)}</a></h3><p>${esc(o.description || "Details und Bedingungen direkt beim Anbieter prüfen.")}</p><div class="meta"><span>${esc(o.advertiser)}</span>${o.endDate ? `<span>bis ${new Intl.DateTimeFormat("de-DE").format(new Date(o.endDate))}</span>` : ""}</div><a class="button" rel="sponsored noopener" href="${esc(o.trackingUrl)}">Zum Angebot <span aria-hidden="true">↗</span></a></article>`;
const empty = `<section class="empty"><span class="empty-icon">◎</span><h2>Noch keine Live-Angebote</h2><p>Die Seite ist technisch bereit. Sobald die Awin-Zugangsdaten hinterlegt sind, erscheinen hier ausschließlich aktive, für Deutschland verfügbare Angebote.</p></section>`;
const homeBody = `<section class="hero"><div><span class="eyebrow">Klar prüfen. Besser entscheiden.</span><h1>Angebote ohne<br><em>Marketingnebel.</em></h1><p>Wir bündeln aktuelle Händleraktionen, zeigen Bedingungen transparent und entfernen abgelaufene Einträge automatisch.</p><a class="button primary" href="#angebote">Aktuelle Angebote ansehen ↓</a></div><aside><strong>Was du hier nicht findest</strong><ul><li>Erfundene Vergleichspreise</li><li>Fake-Bewertungen</li><li>Künstliche Verknappung</li></ul></aside></section><section class="trust"><span>✓ Mehrmals täglich aktualisiert</span><span>✓ Deutschland-Fokus</span><span>✓ Affiliate-Links gekennzeichnet</span></section><section id="angebote" class="offers"><div class="section-head"><div><span class="eyebrow">Live aus Partnerfeeds</span><h2>Aktuelle Angebote</h2></div><label class="search">Angebote durchsuchen<input id="search" type="search" placeholder="z. B. Kopfhörer oder Mode"></label></div><div id="offer-grid" class="grid">${offers.length ? offers.map(card).join("") : empty}</div><p id="no-results" hidden>Keine passenden Angebote gefunden.</p></section><section class="guide"><span class="eyebrow">Kurz erklärt</span><h2>Woran du ein echtes Angebot erkennst</h2><div class="steps"><article><b>01</b><h3>Endpreis prüfen</h3><p>Versand und Zusatzkosten können den Preis verändern. Maßgeblich ist immer die Händlerseite.</p></article><article><b>02</b><h3>Bedingungen lesen</h3><p>Gutscheine können Mindestbestellwerte, Kategorien oder Laufzeiten haben.</p></article><article><b>03</b><h3>Bedarf vor Rabatt</h3><p>Ein Rabatt spart nur dann Geld, wenn du das Produkt ohnehin brauchst.</p></article></div></section>`;
await fs.writeFile(path.join(out, "index.html"), page({ title: "Aktuelle Angebote für Deutschland", description: "Aktuelle, automatisch geprüfte Affiliate-Angebote für Deutschland – ohne Fake-Bewertungen oder erfundene Preise.", canonical: "/", body: homeBody, schema: { "@context":"https://schema.org", "@type":"WebSite", name:config.siteName, url:base } }));
for (const o of offers) {
  const body = `<article class="detail"><a class="back" href="${base}/#angebote">← Alle Angebote</a><span class="pill">${esc(o.category)}</span><h1>${esc(o.title)}</h1><p class="lead">${esc(o.description || "Details direkt beim Anbieter prüfen.")}</p><dl><div><dt>Anbieter</dt><dd>${esc(o.advertiser)}</dd></div>${o.endDate ? `<div><dt>Gültig bis</dt><dd>${new Intl.DateTimeFormat("de-DE", {dateStyle:"long"}).format(new Date(o.endDate))}</dd></div>`:""}${o.voucherCode ? `<div><dt>Gutscheincode</dt><dd><code>${esc(o.voucherCode)}</code></dd></div>`:""}</dl>${o.terms ? `<section><h2>Bedingungen</h2><p>${esc(o.terms)}</p></section>`:""}<p class="notice">Affiliate-Link: Bei einem Kauf können wir eine Provision erhalten. Für dich ändert sich der Preis nicht.</p><a class="button primary" rel="sponsored noopener" href="${esc(o.trackingUrl)}">Angebot beim Händler öffnen ↗</a></article>`;
  await fs.writeFile(path.join(out, "angebote", `${o.slug}.html`), page({ title:o.title, description:o.description || `Aktuelles Angebot von ${o.advertiser}.`, canonical:`/angebote/${o.slug}.html`, body, schema:{"@context":"https://schema.org","@type":"Offer","name":o.title,"url":`${base}/angebote/${o.slug}.html`,"validThrough":o.endDate || undefined,"seller":{"@type":"Organization","name":o.advertiser}} }));
}
const cats = Object.keys(config.categories).map(c => `<li><a href="${base}/?kategorie=${c}#angebote">${esc(c[0].toUpperCase()+c.slice(1))}</a><span>${offers.filter(o=>o.category===c).length}</span></li>`).join("");
await fs.writeFile(path.join(out,"kategorien.html"), page({title:"Kategorien",description:"Alle Angebotskategorien im Überblick.",canonical:"/kategorien.html",body:`<section class="text-page"><span class="eyebrow">Übersicht</span><h1>Kategorien</h1><ul class="category-list">${cats}</ul></section>`}));
const infoPages = {
  "ueber.html": ["Über diese Seite","Angebotslotse bündelt veröffentlichte Händleraktionen aus erlaubten Affiliate-Schnittstellen. Einträge werden automatisiert nach Laufzeit, Region und Datenqualität gefiltert. Wir führen keine eigenen Produkttests durch und erfinden weder Preise noch Bewertungen.","/ueber.html"],
  "affiliate.html": ["Affiliate-Hinweis","Mit „Zum Angebot“ gekennzeichnete Links sind Affiliate-Links. Wenn du darüber einkaufst, können wir eine Provision erhalten. Für dich wird der Kauf dadurch nicht teurer. Die Vergütung beeinflusst nicht, welche Angaben aus den Partnerfeeds übernommen werden.","/affiliate.html"],
  "datenschutz.html": ["Datenschutz","Diese statische Website setzt selbst keine Tracking-Cookies und bindet standardmäßig keine externe Analysesoftware ein. Beim Aufruf werden technisch notwendige Server-Logdaten durch den Hostinganbieter verarbeitet. Beim Klick auf einen Affiliate-Link verlässt du diese Website; beim Zielanbieter gelten dessen Datenschutzhinweise. Verantwortlicher: "+legalName+", "+legalAddress+". Kontakt: "+email+". [JOEL: Hostinganbieter, konkrete Rechtsgrundlagen, Speicherdauer und ggf. eingesetzte Dienste vor Veröffentlichung anwaltlich prüfen und ergänzen.]","/datenschutz.html"],
  "impressum.html": ["Impressum","Angaben gemäß § 5 DDG: "+legalName+", "+legalAddress+". Kontakt: "+email+". Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV: "+legalName+", Anschrift wie vorstehend. [JOEL: Falls zutreffend Rechtsform, Vertretungsberechtigte, Register, Registergericht, Registernummer und USt-IdNr. ergänzen. Vorlage vor Veröffentlichung rechtlich prüfen.]","/impressum.html"],
  "kontakt.html": ["Kontakt","Fragen, Korrekturhinweise oder Meldungen zu abgelaufenen Angeboten bitte an "+email+" senden. Wir bieten keine individuelle Kauf- oder Rechtsberatung.","/kontakt.html"]
};
for (const [file,[title,copy,canonical]] of Object.entries(infoPages)) await fs.writeFile(path.join(out,file),page({title,description:copy.slice(0,150),canonical,body:`<section class="text-page"><span class="eyebrow">Information</span><h1>${esc(title)}</h1>${copy.split("\n").map(p=>`<p>${esc(p)}</p>`).join("")}</section>`}));
await fs.writeFile(path.join(out,"status.html"),page({title:"Systemstatus",description:"Status der letzten Angebotsaktualisierung.",canonical:"/status.html",body:`<section class="text-page"><span class="eyebrow">Transparenz</span><h1>Systemstatus</h1><div class="status ${status.state}"><strong>${status.state === "ok" ? "System betriebsbereit" : "Einrichtung ausstehend"}</strong><p>${esc(status.message)}</p></div><dl><div><dt>Aktive Angebote</dt><dd>${status.activeOffers}</dd></div><div><dt>Letztes erfolgreiches Update</dt><dd>${status.lastSuccessfulUpdate ? new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(status.lastSuccessfulUpdate)) : "Noch keines"}</dd></div><div><dt>Beim letzten Lauf hinzugefügt / entfernt</dt><dd>${status.added} / ${status.removed}</dd></div><div><dt>API-Fehler</dt><dd>${status.apiErrors}</dd></div></dl></section>`}));
await fs.writeFile(path.join(out,"404.html"),page({title:"Seite nicht gefunden",description:"Die angeforderte Seite wurde nicht gefunden.",canonical:"/404.html",body:`<section class="text-page"><span class="eyebrow">Fehler 404</span><h1>Hier ist nichts mehr.</h1><p>Das Angebot ist möglicherweise abgelaufen und wurde automatisch entfernt.</p><a class="button primary" href="${base}/">Zur Startseite</a></section>`}));
const urls = ["/","/kategorien.html","/ueber.html","/affiliate.html","/datenschutz.html","/impressum.html","/kontakt.html","/status.html",...offers.map(o=>`/angebote/${o.slug}.html`)];
await fs.writeFile(path.join(out,"sitemap.xml"),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${base}${u}</loc></url>`).join("")}</urlset>`);
await fs.writeFile(path.join(out,"robots.txt"),`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);
